<a href="https://colab.research.google.com/github/mateuszrajca69/Chess/blob/master/kurier_praca_inz_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tsp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 14.2 MB 5.2 MB/s 


In [2]:
pip install python-tsp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 62 kB 1.1 MB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


In [3]:
import tsp
import numpy as np
import matplotlib.pyplot as plt
import time

In [4]:

#DANE
#https://dateandtime.info/pl/citycoordinates.php?id=3094802
#https://www.wspolrzedne-gps.pl

In [5]:
all_cit=np.array([
             [50.853865,20.608938],#Hotel Bińkowski
             [50.875366,20.624609],#Hotel Qubus
    [50.869045,20.627616],#Muzeum Narodowe w Kielcach
    [50.894032,20.577591],#Park Rozrywki FlySky
    [50.87033,20.62752],#Szkoła Podstawowa Nr 25
    [50.883909,20.605892],#ZUS
    [50.873259,20.618311],#Poczta Polska
    [50.869286,20.614102],#Kościół Niepokalanego Serca NMP w Kielcach
    [50.867662,20.61716],#Paczkomat InPost
    [50.865725,20.624095],#Żłobek /Klub Malucha "Radosna Kraina"
    [50.865091,20.626189],#MOSiR, Pływalnia Delfin
    [50.863718,20.623781],#Uniwersytet Jana Kochanowskiego, Wydział Pedagogiki i Psychologii
    [50.86042,20.627478],#I Liceum Ogólnokształcące im. Stefana Żeromskiego w Kielcach
    [50.854364,20.616447],#Wojskowa Specjalistyczna Przychodnia Lekarska SPZOZ w Kielcach
    [50.8428,20.613668],#Pensjonat Villa Romano
    [50.831859,20.662217],#Centrum Przygotowań do Misji Zagranicznych w Kielcach
    [50.83926,20.657629],#Wojewódzki Sztab Wojskowy w Kielcach
    [50.842109,20.642066],#Telegraf Kielce
    [50.833886,20.657233],#Leśna Sauna
    [50.857751,20.653476],#Cygański Zamek przy Liroyu
    [50.881285,20.6152],#Urząd Miasta Kielce Wydział Geodezji
    [50.872329,20.615078],#Wytwórcza Spółdzielnia Pracy Społem Kielce
    [50.860612,20.62492],#Korona Kielce
    [50.8333,20.6667],#Wszechnica Świętokrzyska w Kielcach
    [50.904139,20.639624],#Wyższa Szkoła Handlowa im. Bolesława Markowskiego
    [50.911923,20.637494],#Areszt Śledczy w Kielcach
    [50.897308,20.580053],#Parafia MB Częstochowskiej w Kielcach-Niewachlowie
    [50.898911,20.586778],#Targi Kielce
    [50.899369,20.597969],#Karczma Pod Strzechą
    [50.885275,20.587875],#Parafia bł. Jerzego Matulewicza w Kielcach
    [50.800681,20.61911],#Hotel Dyminy
    [50.881134,20.646247],#Galeria Echo
    [50.881125,20.639552],#ŚCITT Sp. z o.o. - Świętokrzyskie Centrum Innowacji i Transferu Technologii Sp. z o.o.
    [50.885516,20.641972],#KebaR Kebab 
    [50.881285,20.6152],#Urząd Miasta Kielce Wydział Geodezji
    [50.872329,20.615078],#Wytwórcza Spółdzielnia Pracy Społem Kielce
    [50.860612,20.62492],#Korona Kielce
    [50.871964,20.631833],#Maska Incognito Club
    [50.8333,20.6667],#Świętokrzyski Oddział Wojewódzki NFZ
    [50.869621,20.63462],#Kawiarnia Choco Obsession
    [50.866663,20.635995],#Filharmonia Świętokrzyska im. Oskara Kolberga
    
    
    
    
    
    
  
            
])

n=len(all_cit)

In [6]:
n

41

In [7]:
import math as m

In [8]:
def dist(i,j):
    R=6400
    if i == j:
        return 0
    else:
        return R*np.arccos((m.sin(all_cit[i,1]/180)*m.sin(all_cit[j,1]/180) +
               m.cos(all_cit[i,1]/180)*m.cos(all_cit[j,1]/180)*m.cos((all_cit[i,0]/180)-(all_cit[j,0]/180))))

In [9]:
dist(1,2)

0.24755133217906583

In [10]:
all_cit[0]

array([50.853865, 20.608938])

In [11]:
def all_dist(i,j): # funkcja odległości między wszystkimi miastami
    return np.sqrt((all_cit[i,0]-all_cit[j,0])**2 + (all_cit[i,1]-all_cit[j,1])**2)

In [12]:
dt=[[dist(i,j) for i in range(n)] for j in range(n)]
np.round(np.array(dt),2)

array([[0.  , 0.94, 0.85, ..., 2.18, 1.07, 1.06],
       [0.94, 0.  , 0.25, ..., 2.11, 0.41, 0.51],
       [0.85, 0.25, 0.  , ..., 1.88, 0.25, 0.31],
       ...,
       [2.18, 2.11, 1.88, ..., 0.  , 1.72, 1.61],
       [1.07, 0.41, 0.25, ..., 1.72, 0.  , 0.12],
       [1.06, 0.51, 0.31, ..., 1.61, 0.12, 0.  ]])

In [13]:
# konwersja tablicy odległości do słownika (potrzebne dalej dla wołania f. bibliotecznej)
dis = {(i, j): dt[i][j] for i in range(n) for j in range(n)}

In [14]:
dis

{(0, 0): 0,
 (0, 1): 0.9419437465998142,
 (0, 2): 0.853547991901025,
 (0, 3): 1.804246227395679,
 (0, 4): 0.88020325210379,
 (0, 5): 1.0667500724848753,
 (0, 6): 0.7618096394837374,
 (0, 7): 0.5748241150315337,
 (0, 8): 0.5683030473631637,
 (0, 9): 0.6825898656992354,
 (0, 10): 0.7303823263281566,
 (0, 11): 0.63217764881181,
 (0, 12): 0.6986809727985213,
 (0, 13): 0.26756785686192236,
 (0, 14): 0.4254928767977173,
 (0, 15): 2.0476354948655136,
 (0, 16): 1.806463306027432,
 (0, 17): 1.2489372791901656,
 (0, 18): 1.8565126837692802,
 (0, 19): 1.589511070880614,
 (0, 20): 0.9938099310703972,
 (0, 21): 0.6877661345595013,
 (0, 22): 0.6162012047232939,
 (0, 23): 2.1784365813242466,
 (0, 24): 2.0841952289337873,
 (0, 25): 2.2883313418527083,
 (0, 26): 1.8465076656734247,
 (0, 27): 1.7755549714455154,
 (0, 28): 1.6539725319453105,
 (0, 29): 1.3385967763830715,
 (0, 30): 1.913097722261849,
 (0, 31): 1.6393529254976176,
 (0, 32): 1.4532662628244029,
 (0, 33): 1.6215575075162036,
 (0, 34): 0.993

In [15]:
time0 = time.time()    # czas start
t_tsp = tsp.tsp(range(n),dis) # znajdź DOKŁADNE rozwiązanie
time1 = time.time()    # czas stop

print(t_tsp)
print("czas wykonania:",round(time1 - time0,1),"s")

(14.571057026696863, [0, 14, 30, 17, 18, 15, 38, 23, 16, 19, 40, 39, 37, 32, 31, 33, 24, 25, 28, 27, 26, 3, 29, 5, 34, 20, 21, 35, 7, 8, 6, 1, 4, 2, 10, 9, 11, 12, 36, 22, 13])
czas wykonania: 1245.5 s


In [16]:
p_tsp=np.array(t_tsp[1]) # najkrótsza trasa
t_tsp[0] # długość najkrótszej trasy

14.571057026696863

In [17]:
#Komórka ta powoduje zamknięcie trasy 
t=t_tsp[1]
index=0
route=np.insert(np.append(t,0),0,0)
route=np.delete(route,index)
tour=np.array([all_cit[i] for i in route])
tour

array([[50.853865, 20.608938],
       [50.8428  , 20.613668],
       [50.800681, 20.61911 ],
       [50.842109, 20.642066],
       [50.833886, 20.657233],
       [50.831859, 20.662217],
       [50.8333  , 20.6667  ],
       [50.8333  , 20.6667  ],
       [50.83926 , 20.657629],
       [50.857751, 20.653476],
       [50.866663, 20.635995],
       [50.869621, 20.63462 ],
       [50.871964, 20.631833],
       [50.881125, 20.639552],
       [50.881134, 20.646247],
       [50.885516, 20.641972],
       [50.904139, 20.639624],
       [50.911923, 20.637494],
       [50.899369, 20.597969],
       [50.898911, 20.586778],
       [50.897308, 20.580053],
       [50.894032, 20.577591],
       [50.885275, 20.587875],
       [50.883909, 20.605892],
       [50.881285, 20.6152  ],
       [50.881285, 20.6152  ],
       [50.872329, 20.615078],
       [50.872329, 20.615078],
       [50.869286, 20.614102],
       [50.867662, 20.61716 ],
       [50.873259, 20.618311],
       [50.875366, 20.624609],
       [

In [18]:
lenpa=np.round(t_tsp[0],3) # długość najkrótszej trasy
lenpa

14.571

In [19]:

!pip install folium

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [20]:

import folium

In [21]:
my_map = folium.Map([50.854036,20.609914])
for i in tour:
    
    folium.Marker(i).add_to(my_map)

my_map

In [22]:
my_map = folium.Map([50.854036,20.609914])
for i in tour:
    folium.Marker(i).add_to(my_map)
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map

In [23]:
my_map = folium.Map([50.854036,20.609914])
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map